import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import ConfigProviders from "@/components/providers/config.providers";
import { Header, HeaderMenu } from "@/entities/header";
import { Search } from "@/entities/search";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased font-(var(--font-rubik))`}
      >
        <ConfigProviders>
          <div className="wrapper">
            {children}
          </div>
        </ConfigProviders>
      </body>
    </html>
  );
}
